#!/bin/bash

# The pre_start_cartridge and pre_stop_cartridge hooks are *SOURCED*
# immediately before (re)starting or stopping the specified cartridge.
# They are able to make any desired environment variable changes as
# well as other adjustments to the application environment.

# The post_start_cartridge and post_stop_cartridge hooks are executed
# immediately after (re)starting or stopping the specified cartridge.

# Exercise caution when adding commands to these hooks.  They can
# prevent your application from stopping cleanly or starting at all.
# Application start and stop is subject to different timeouts
# throughout the system.

pushd "$OPENSHIFT_REPO_DIR" > /dev/null
[ ! -f config.ru ] && wget http://www.redmine.org/releases/redmine-2.4.1.tar.gz
tar --strip-components=1 -zxvf redmine-2.4.1.tar.gz
bundle install --no-deployment
popd > /dev/null