#!/bin/bash
# This is a simple script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

#
#  main(): Add a Gemfile.lock from the specific version and replace the env
#          variables for DB HOST, USERNAME and PASSWORD.
# 
pushd "$OPENSHIFT_REPO_DIR" > /dev/null
wget http://www.redmine.org/releases/redmine-2.4.1.tar.gz
tar --strip-components=1 -zxvf redmine-2.4.1.tar.gz
bundle install --no-deployment
